### ISSUE TITLE
Authenticated images can't accessed

### ISSUE THREAD

**Issue by imwaddy** [laurenashpole/vue-inner-image-zoom#4]
I have used the module in my project but the issue is my CDN server only serves resources **the requests with authentication**. I have come to know that the authentication is not happening in the module.

Please add an authentication mechanism with the src request while loading the image.

For a reference: https://gitlab.com/jlalande/vue-auth-image

**Comment by laurenashpole** [comment]
Sorry for the extreme delay responding to this message. 

I'm not sure that this use case is common enough to include it in the package especially if it requires an additional dependency. Looking at the reference you linked, it might make more sense to pull out their logic for requesting and encoding images that require authentication and add it to your project.

I'm closing this for now but would definitely reconsider if it turns out this issue is more prevalent than I'd imagined.
