### ISSUE TITLE
vue 3 support

### ISSUE THREAD

**Issue by raithorivera** [laurenashpole/vue-inner-image-zoom#6]
will it have vue3 support? as vue3 removes the Vue.extend and it produces error

**Comment by schmeiger** [comment]
I would also love to have vue 3 support for this awesome image viewer :)

**Comment by ascottmccauley** [comment]
Samesies...

**Comment by laurenashpole** [comment]
Sorry I'm a little slow responding to these! Things have been a little hectic but I have some time to devote to this project now. I'll be starting with porting over some of the functionality from the [React version](https://github.com/laurenashpole/react-inner-image-zoom#props) (zoom on hover, image scale, responsive image spacers, etc.) and once that's done Vue 3 support is next on the list.

**Comment by laurenashpole** [comment]
Okay that took way, way longer than expected but it turns out I really needed the official Vue migration build to upgrade the component and demos. I just published v2.0.0 for use with Vue 3. 

Thanks so much for your patience! I'll be closing this issue now but definitely open new ones if you run into any bugs.

**Comment by schmeiger** [comment]
Cool! Thank you! :)
